# Generated by Django 3.2.4 on 2021-09-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
    ]
