# Generated by Django 3.2.4 on 2021-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='email',
            field=models.CharField(default='none', max_length=120),
        ),
        migrations.AddField(
            model_name='lab',
            name='tel2',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='telephone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lab',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
